channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.0.1
- pip:
  - mlflow==3.4.0
  - numpy==2.1.3
  - pandas==2.2.3
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.15.1
  - xgboost==3.0.5
name: mlflow-env
